Group_page_map:
  description: "This applies when the primary group of the user.<br>Input it as group_name:URL. Can be several entries.<br>For example, trust_level_1:/latest"
  type: list
  default: ""
Anon_page:
  description: "The URL for users who aren't logged in.<br>If left blank, will use site default."
  type: string
  default: ""
Mobile_homepage:
  description: "What mobile users see. If left blank, will be the same as above"
  type: enum
  default: ""
  choices:
    - latest
    - categories
    - new
    - unread
    - top
