group_page_map:
  description: "Group_name:URL list as <br>For example, trust_level_1:/latest"
  type: list
  default: ""
anon_page:
  description: "The URL for users who aren't logged in"
  type: string
  default: ""
